global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'simulator'
    static_configs:
      - targets: ['simulator:9090']
    scrape_interval: 5s

  - job_name: 'bancaire'
    static_configs:
      - targets: ['bancaire:9090']
    scrape_interval: 5s

  - job_name: 'gateway'
    static_configs:
      - targets: ['gateway:9090']
    scrape_interval: 5s
